### ISSUE TITLE
Can you tell me what i am doing incorrect - pls

### ISSUE THREAD

**Issue by SimonDev666** [CleasbyCode/pdvzip#1]
Hello,

found your solution and it looks really good, just can not get it to work. i am using Kali linux 2024.2. 

got your code to compile, just when i run a similar approach to your python demo, i get an 'zsh: exec format error: ./Fibo.png'. i have tried to follow your example, but seem to be doing something wrong.

any chance of any advice please.

i enclose my demo parts.
[fib.py.zip](https://github.com/user-attachments/files/16096039/fib.py.zip)
Image001.png
![Image001](https://github.com/CleasbyCode/pdvzip/assets/126995447/94edd0a8-5136-42c6-9605-1d705acb73dc)
pzip_90106.png
![pzip_90106](https://github.com/CleasbyCode/pdvzip/assets/126995447/a888d884-91a1-4200-be29-1152aa76ec16)

many thanks for any help,

Simon

**Comment by CleasbyCode** [comment]
Your image file runs the python with both my Linux and Windows, but I have not tested it with Kali Linux, just Ubuntu, Fedora.
You have python3?
You gave the image file executable permissions? 
Does the image run in Windows (You need to rename the .png extension to .cmd)?
I will install and test Kali.

**Comment by CleasbyCode** [comment]
The issue is with **zsh**, which I have not tested (!). I'll see if I can do anything about it, until then, try a different shell.
For now, within your **zsh**, you would have to use:  **bash ./image_file.png**
Thanks for bringing this to my attention.

**Comment by SimonDev666** [comment]
thanks for the quick reply. i am using python 3.12. Kali linux is the 64 bit version. i will try that which you have suggested.

the idea behind using this approach is for my dissertation. i want to email a simple html containing one of your coerced images and then get it to run (if i can). i have been playing with zipped SFX files using RTLO filename encoding, but it a big ask to get the user to run something that looks not quite right. i my demo for this i encoded a metasploit backdoor in it and it works, just the filename that does not look right. hence trying your concept.

is you approach all 64bit??

**Comment by SimonDev666** [comment]
an update, whilst the zsh seems to fail, the bash approach works !!!!! excellant. i did freck a bit when i ran you png and got lots of images. the python variant also works.

my idea is to send a user a faked email (from admin on his domain) which contains a simple html and images - nothing to alarm anyone or thing on the target machine - not like the rtlo approach. in my scenario, i have a windows xp machine running with the firewall up, but with simple connectivity out ward (http, ftp, smtp, etc). so an attacker can not get through easily. my dissertaion will not show any exotic approachs to hacking, as a.) i dont know that many and b.) i dont think my profs would like me to teach others really naughty concepts - thats not what i want my dissetaion to be about. but in its use of an AI approach to planning all its actions given a goal it has to achieve. it uses a GOAP (goal oriented action planner) type approach, so in order to achieve a goal, the AI puts together from a bucket of many possible atomic actions a solution. its used in games and i have used it to control a UAV (in simulation)

i chose xp (32bit) as its a typical target machine, plus i have all the usual vulnerable variants (metasploitable 2/3, dvwa, etc). i do have a windows 7 64 bit vm, which i will start using for this emailing concept. i could switch up to windows 10.

i must make the point, this is for my dissertaion and not for any illegal activities. in doing my MSc i am fully aware of the penalties for doing anything naughty. i will be guided by my uni profs what i can actually do. but the underlying idea is not beat down the door on the target machine, but get round its simple defences through social engineering (faked email). of course on a fully defended target machine, you would hope the AV would catch this approach ASAP when it trys to run
